# Docker compose to set up containers for all services you need:
#   
#   Minecraft
#   RWA-RCON
#   cAdvisor
#   Docker Socket Proxy
#
# Before running docker-compose, you should pre-create all of the following folders.

# Folders for Docker State:
# /dockerdata                       - docker root 
# /dockerdata/minecraft             - MC config

# Folders for media
# Be sure to mounted folders
# Permissions for all NFS shares should be 740
# <NAS_IP>/volume1/Minecraft                 - Minecraft jar file; Mounted locally to /MC

version: "3"
services:

########################################################

# Minecraft

########################################################

# Minecraft Java Edition Server
  mc:
    image: itzg/minecraft-server
    container_name: Minecraft-Java
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TZ: AMERICA/CHICAGO
      MOTD: "Welcome To The NipRip"
      OVERRIDE_SERVER_PROPERTIES: "true"
      DEBUG: "true"

      # Hardware configs
      MEMORY: 13G
      VIEW_DISTANCE: 10
      MAX_PLAYERS: 10

      # Permissions based settings
      PVP: "false"
      CONSOLE: "false"
      ALLOW_FLIGHT: "true"
      OPS: "PostWarTacos"

      # MODS
      TYPE: AUTO_CURSEFORGE
      VERSION: 1.19.2
      FORGE_VERSION: 43.2.21
      CF_API_KEY: '$2a$10$1mcx8G4FszeBFWuwtvgmOeC/e0VogiSVGk/fgSIhTcMns1YiULFn2'
      #CF_PAGE_URL: 'https://www.curseforge.com/minecraft/modpacks/niprip/files/4687503'
      CF_SLUG: niprip
      # CF_FILE_ID: 4687503 # v1.0
      # CF_FILE_ID: 4734216 # v1.2.1
      # CF_FILE_ID: 4744527 # v1.3
      # CF_FILE_ID:  4744623 # v1.3.1
      # CF_FILE_ID:  4751482 # v1.3.1.1
      # CF_FILE_ID:  4760856 # v1.3.1.2
      # CF_FILE_ID:  4764477 # v1.3.2
      # CF_FILE_ID:  4773172 # v1.3.3
      # CF_FILE_ID:  4774411 # v1.3.4
      CF_FILE_ID:  4780900 # v1.3.5
      
      # needs to match RWA_RCON_PASSWORD on web container
      RCON_PASSWORD: "ncc2cmC3_Ht9YRLnN!QZ"
    volumes:
      - /MC:/data
      - /MC/modpacks:/modpacks:ro
    restart: unless-stopped

# RWA RCON
  web:
    image: itzg/rcon
    container_name: RWA-RCON
    ports:
      - 4326:4326
      - 4327:4327
    environment:
      TZ: AMERICA/CHICAGO

      # UN and PW to RWA UI
      RWA_USERNAME: "matt_rwa"
      RWA_PASSWORD: "uf98idoBWF83gs@z@pm7"
      RWA_ADMIN: "TRUE"

      # is referring to the hostname of 'mc' compose service above
      RWA_RCON_HOST: mc

      # needs to match the RCON_PASSWORD configured for the container
      RWA_RCON_PASSWORD: "ncc2cmC3_Ht9YRLnN!QZ"
    restart: unless-stopped
    depends_on:
      - mc

########################################################

# Monitoring

########################################################
     
# cAdvisor
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor-arm64:v0.47.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    environment:
      detach: "true"
    ports:
      - 8282:8080
    restart: unless-stopped
    
########################################################

# Docker Management

########################################################

# Docker Socket Proxy
  socket-proxy:
    container_name: docker-socket-proxy
    image: tecnativa/docker-socket-proxy
    privileged: true
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
    restart: unless-stopped