
version: "3"
services:

########################################################

# Docker Management

########################################################

# Docker Socket Proxy
  socket-proxy:
    container_name: docker-socket-proxy
    image: tecnativa/docker-socket-proxy
    privileged: true
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
    restart: unless-stopped
    
