version: "3"

services:

# cAdvisor
  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor-arm64:v0.47.2
    volumes:
      - /:/rootfs:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /proc/cpuinfo:/proc/cpuinfo:ro
      - /dev/kmsg:/dev/kmsg:rw
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    # environment:
      # detach: "true"
    ports:
      - 8282:8080
    privileged: "true"
    restart: unless-stopped